#!/usr/bin/env python3
"""Fill in the package-manager manifests for a release.

Reads the templates under packaging/manifests/ (winget, Scoop, Homebrew) and the Flatpak
manifest under packaging/flatpak/, and writes ready-to-submit copies with the version, the
release tag, the release date, the tag's commit and the SHA-256 checksums of the packages:

    python3 packaging/manifests/update_manifests.py --tag v1.0.0
    python3 packaging/manifests/update_manifests.py --tag v1.0.0 \
        --checksums dist/SHA256SUMS.txt --commit 0123abc... --output build/manifests

Without --checksums the SHA256SUMS.txt of the GitHub release is downloaded; without --commit
the commit is read from the local tag. The output layout matches the target repositories:

    winget/manifests/d/DimitriosKafetzis/NMEASimulatorX/<version>/*.yaml
    scoop/bucket/nmeasimulatorx.json
    homebrew/Casks/nmeasimulatorx.rb
    flathub/io.github.dimitrios_kafetzis.NMEASimulatorX.yml

Only the Python standard library is used. The how-to docs/how-to/submit-package-manifests.md
explains how each file is submitted.
"""

import argparse
import datetime
import pathlib
import re
import subprocess
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[2]
TEMPLATES = ROOT / "packaging" / "manifests"
FLATPAK_MANIFEST = ROOT / "packaging" / "flatpak" / "io.github.dimitrios_kafetzis.NMEASimulatorX.yml"
REPOSITORY = "Dimitrios-Kafetzis/NMEA_Simulator_X"
WINGET_ID = "DimitriosKafetzis.NMEASimulatorX"

# Placeholder -> package file name, with {version} standing for the package version.
PACKAGES = {
    "SHA256_WIN64_EXE": "NMEASimulatorX-{version}-win64.exe",
    "SHA256_WIN64_ZIP": "NMEASimulatorX-{version}-win64-portable.zip",
    "SHA256_MACOS_ARM64": "NMEASimulatorX-{version}-macos-arm64.dmg",
    "SHA256_MACOS_X86_64": "NMEASimulatorX-{version}-macos-x86_64.dmg",
}

TAG_PATTERN = re.compile(r"^v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)$")
DIR_SOURCE = re.compile(r"^(?P<indent> *)- type: dir\n(?:(?P=indent)  .*\n)+", re.MULTILINE)


def read_checksums(text: str) -> dict[str, str]:
    checksums = {}
    for line in text.splitlines():
        if not line.strip():
            continue
        digest, name = line.split(maxsplit=1)
        checksums[name.lstrip("*").strip()] = digest.lower()
    return checksums


def download_checksums(tag: str) -> str:
    url = f"https://github.com/{REPOSITORY}/releases/download/{tag}/SHA256SUMS.txt"
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def tag_commit(tag: str) -> str:
    result = subprocess.run(["git", "rev-list", "-n", "1", tag], cwd=ROOT, capture_output=True,
                            text=True, check=True)
    return result.stdout.strip()


def fill(template: str, values: dict[str, str]) -> str:
    def replace(match: re.Match) -> str:
        key = match.group(1)
        if key not in values:
            raise KeyError(f"no value for placeholder @{key}@")
        return values[key]

    filled = re.sub(r"@([A-Z0-9_]+)@", replace, template)
    return "\n".join(line for line in filled.splitlines()
                     if not line.startswith("# Template:")) + "\n"


def flathub_manifest(tag: str, commit: str) -> str:
    text = FLATPAK_MANIFEST.read_text(encoding="utf-8")
    match = DIR_SOURCE.search(text)
    if match is None:
        raise ValueError(f"no '- type: dir' source in {FLATPAK_MANIFEST}")
    indent = match.group("indent")
    git_source = (f"{indent}- type: git\n"
                  f"{indent}  url: https://github.com/{REPOSITORY}.git\n"
                  f"{indent}  tag: {tag}\n"
                  f"{indent}  commit: {commit}\n")
    header_end = text.index("\nid:")
    header = ("# Flathub manifest of NMEA Simulator X " + tag + ", generated by\n"
              "# packaging/manifests/update_manifests.py from packaging/flatpak/.\n")
    return header + text[header_end + 1:match.start()] + git_source + text[match.end():]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tag", required=True, help="release tag, e.g. v1.0.0")
    parser.add_argument("--checksums", type=pathlib.Path,
                        help="SHA256SUMS.txt of the release (downloaded when omitted)")
    parser.add_argument("--commit", help="commit of the tag (read from git when omitted)")
    parser.add_argument("--date", default=datetime.datetime.now(datetime.timezone.utc).date()
                        .isoformat(), help="release date, YYYY-MM-DD (default: today, UTC)")
    parser.add_argument("--output", type=pathlib.Path, default=ROOT / "build" / "manifests")
    args = parser.parse_args()

    match = TAG_PATTERN.match(args.tag)
    if match is None:
        parser.error(f"tag {args.tag} is not of the form vX.Y.Z")
    version = match.group(1)
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", args.date):
        parser.error(f"date {args.date} is not of the form YYYY-MM-DD")

    text = (args.checksums.read_text(encoding="utf-8") if args.checksums
            else download_checksums(args.tag))
    checksums = read_checksums(text)
    values = {"VERSION": version, "TAG": args.tag, "RELEASE_DATE": args.date}
    missing = []
    for key, pattern in PACKAGES.items():
        name = pattern.format(version=version)
        if name in checksums:
            values[key] = checksums[name]
        else:
            missing.append(name)
    if missing:
        print("SHA256SUMS.txt lacks: " + ", ".join(missing), file=sys.stderr)
        return 1
    # winget writes installer hashes in upper case.
    values["SHA256_WIN64_EXE"] = values["SHA256_WIN64_EXE"].upper()
    commit = args.commit or tag_commit(args.tag)
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        print(f"commit {commit!r} is not a full SHA-1", file=sys.stderr)
        return 1

    outputs = {
        pathlib.Path("scoop/bucket/nmeasimulatorx.json"): TEMPLATES / "scoop/nmeasimulatorx.json",
        pathlib.Path("homebrew/Casks/nmeasimulatorx.rb"): TEMPLATES / "homebrew/nmeasimulatorx.rb",
    }
    winget_dir = pathlib.Path("winget/manifests/d/DimitriosKafetzis/NMEASimulatorX") / version
    for suffix in ("", ".installer", ".locale.en-US"):
        name = f"{WINGET_ID}{suffix}.yaml"
        outputs[winget_dir / name] = TEMPLATES / "winget" / name

    for relative, template in outputs.items():
        target = args.output / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(fill(template.read_text(encoding="utf-8"), values), encoding="utf-8")
        print(target)
    target = args.output / "flathub" / FLATPAK_MANIFEST.name
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(flathub_manifest(args.tag, commit), encoding="utf-8")
    print(target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
